#!/bin/sh
### BEGIN INIT INFO
# Provides:          ocvsmd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SysV script for ocvsmd
# Description:       This service manages the OpenCyphal Vehicle System Management Daemon (OCVSMD).
### END INIT INFO

DAEMON_NAME="ocvsmd"
DAEMON_PATH="/usr/local/bin/ocvsmd"
PIDFILE="/var/run/${DAEMON_NAME}.pid"

case "$1" in
    start)
        echo "Starting $DAEMON_NAME..."
        if [ -f $PIDFILE ]; then
            echo "$DAEMON_NAME is already running."
            exit 1
        fi
        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON_PATH
        echo "$DAEMON_NAME started."
        ;;
    stop)
        echo "Stopping $DAEMON_NAME..."
        if [ ! -f $PIDFILE ]; then
            echo "$DAEMON_NAME is not running."
            exit 1
        fi
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        rm -f $PIDFILE
        echo "$DAEMON_NAME stopped."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            if kill -0 "$PID" >/dev/null 2>&1; then
                echo "$DAEMON_NAME is running (PID $PID)."
            else
                echo "$DAEMON_NAME is not running, but pidfile exists."
            fi
        else
            echo "$DAEMON_NAME is not running."
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0
